In [3]:
import pandas as pd
import numpy as np
import sys

In [4]:
# Create reference to CSV file
csv_path1 = "raw_data/election_data_1.csv"
csv_path2 = "raw_data/election_data_2.csv"

In [29]:
elecD1 = pd.read_csv(csv_path1)
elecD2 = pd.read_csv(csv_path2)
elecD1.head()

   Voter ID      County Candidate
0   1405627      Harsaw    Vestal
1   1711723  Mershville    Vestal
2   1550639  Matterdawn    Vestal
3   1042621      Harsaw    Vestal
4   1583965  Matterdawn    Vestal

In [30]:
#Total Number of Votes
Votes1 = len(elecD1.index)
Votes2 = len(elecD2.index)
TotVotes = Votes1 + Votes2

In [31]:
#Get Unique Candidates
Candidates1 = elecD1.Candidate.unique()
Candidates2 = elecD2.Candidate.unique()

In [32]:
#Print list of Candidates
#print("List of Candidates that recieved votes:")
#print(*Candidates1, sep = "\n")
#print(*Candidates2, sep = "\n")

In [33]:
# Candidates1 = elecD1['Candidate'].value_counts().index.tolist
# Votes1 = elecD1['Candidate'].value_counts().tolist
# Candidates2 = elecD2['Candidate'].value_counts().keys().tolist
# Votes2 = elecD2['Candidate'].value_counts().tolist

In [44]:
for column in elecD1:
    if elecD1["Candidates"]==
    print(elecD1[column])

0         1405627
1         1711723
2         1550639
3         1042621
4         1583965
5         1943299
6         1880982
7         1305689
8         1759114
9         1745020
10        1562401
11        1467337
12        1091170
13        1947604
14        1400758
15        1009045
16        1246891
17        1744120
18        1571939
19        1936895
20        1122582
21        1307503
22        1594030
23        1072081
24        1368919
25        1954121
26        1427438
27        1049416
28        1619112
29        1725473
           ...
802970    1243711
802971    1165617
802972    1536635
802973    1952569
802974    1900901
802975    1623227
802976    1164899
802977    1430310
802978    1421648
802979    1966539
802980    1048447
802981    1220171
802982    1546597
802983    1454316
802984    1273447
802985    1642944
802986    1009803
802987    1348943
802988    1984510
802989    1242544
802990    1370412
802991    1071339
802992    1232786
802993    1872696
802994    1818021
802995    1165505
802996    1923858
802997    1959786
802998    1768101
802999    1320393
Name: Voter ID, Length: 803000, dtype: int64
0             Harsaw
1         Mershville
2         Matterdawn
3             Harsaw
4         Matterdawn
5         Mershville
6             Harsaw
7             Harsaw
8         Mershville
9         Matterdawn
10            Harsaw
11            Porpus
12        Matterdawn
13            Harsaw
14        Mershville
15        Matterdawn
16        Matterdawn
17        Matterdawn
18        Mershville
19        Matterdawn
20        Matterdawn
21        Mershville
22            Harsaw
23        Mershville
24        Mershville
25            Harsaw
26        Matterdawn
27            Porpus
28            Harsaw
29        Mershville
             ...
802970        Porpus
802971        Harsaw
802972        Porpus
802973    Mershville
802974        Harsaw
802975    Mershville
802976        Porpus
802977        Porpus
802978    Mershville
802979    Matterdawn
802980        Arrent
802981        Arrent
802982    Matterdawn
802983        Harsaw
802984    Matterdawn
802985    Matterdawn
802986        Harsaw
802987        Porpus
802988    Mershville
802989        Porpus
802990        Harsaw
802991        Porpus
802992        Porpus
802993    Matterdawn
802994        Porpus
802995        Harsaw
802996        Harsaw
802997    Matterdawn
802998    Matterdawn
802999        Harsaw
Name: County, Length: 803000, dtype: object
0         Vestal
1         Vestal
2         Vestal
3         Vestal
4         Vestal
5         Vestal
6         Torres
7         Torres
8         Vestal
9           Seth
10        Vestal
11        Torres
12        Torres
13        Vestal
14        Torres
15        Vestal
16        Cordin
17        Vestal
18        Vestal
19        Vestal
20        Torres
21        Torres
22        Torres
23        Torres
24        Vestal
25        Torres
26        Vestal
27        Torres
28        Torres
29        Vestal
           ...
802970    Cordin
802971    Vestal
802972    Torres
802973    Vestal
802974    Vestal
802975    Torres
802976    Torres
802977    Torres
802978    Vestal
802979    Vestal
802980    Vestal
802981    Vestal
802982    Torres
802983    Vestal
802984    Vestal
802985    Torres
802986    Torres
802987    Vestal
802988    Vestal
802989    Vestal
802990    Torres
802991    Vestal
802992    Vestal
802993    Torres
802994    Vestal
802995    Vestal
802996    Torres
802997    Torres
802998    Torres
802999    Torres
Name: Candidate, Length: 803000, dtype: object